[package]
name = "xcm-ce-sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
ink = { version = "~4.2.0", default-features = false }

num_enum = { version = "0.6", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.39", default-features = false }
xcm-ce-primitives = { path = "../primitives", default-features = false }

[lib]
path = "lib.rs"

# [profile.release]
# overflow-checks = false # Disable integer overflow checks.

[features]
default = ["std"]
std = [
	"ink/std",
	"num_enum/std",
	"scale/std",
	"scale-info/std",
	"xcm/std",
	"xcm-ce-primitives/std",
]
ink-as-dependency = []
