[package]
name = "assets-chain-extension-types"
version = "0.1.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://astar.network"
repository = "https://github.com/AstarNetwork/astar-frame"
description = "Types definitions forassets chain-extension"

[dependencies]
ink_primitives = { version = "3.4.0", default-features = false,  optional = true }
ink_env = { version = "3.4.0", default-features = false, optional = true }
ink_storage = { version = "3.4.0",default-features = false, optional = true }
ink_metadata = { version = "3.4.0", default-features = false, features = ["derive"], optional = true }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }

sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }

[features]
default = ["std"]
substrate = [
    "scale-info/std",
    "scale/std",
    "sp-runtime/std",
]
ink = [
    "scale-info/std",
    "scale/std",
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "sp-runtime/std",
]
std = [
    "scale-info/std",
    "scale/std",
    "sp-runtime/std",
]