[package]
name = "dapps-staking-chain-extension-types"
version = "1.1.0"
license = "Apache-2.0"
description = "Types definitions for dapps-staking chain-extension"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true, package = "parity-scale-codec" }
frame-support = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
]
