[package]
name = "xcm-primitives"
version = "0.3.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
description = "Common XCM primitives used by runtimes"
edition = "2021"

[dependencies]

# third-party dependencies
log = { version = "0.4", default-features = false }

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }

# XCM dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24", default-features = false }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.24", default-features = false }

# Astar pallets
pallet-xc-asset-config = { path = "../../frame/xc-asset-config", default-features = false }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"sp-std/std",
	"sp-runtime/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"pallet-xc-asset-config/std",
]
