[package]
name = "xcm-primitives"
version = "0.1.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
description = "Common XCM primitives used by runtimes"
edition = "2021"

[dependencies]

# third-party dependencies
log = { version = "0.4", default-features = false }

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }

# XCM dependencies
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.19" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.19" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.19" }

# Astar pallets
pallet-xc-asset-config = { git = "https://github.com/AstarNetwork/astar-frame", default-features = false, branch = "polkadot-v0.9.19" }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-std/std",
    "sp-runtime/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "pallet-xc-asset-config/std",
]
