name: Checks and Tests
on: [push, workflow_dispatch]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check all features compilation
      run: cargo check --release --all-features --verbose

    - name: Run all tests
      run: cargo test --all-features

    - name: Cleanup after tests
      run: cargo clean

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage report
      run: cargo tarpaulin --verbose -o=Html

    - uses: actions/upload-artifact@master
      with:
        name: coverage-report.html
        path: tarpaulin-report.html
