on: [push]

name: Integration

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Check if code compiles
      run: cargo check --release --all-features --verbose

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Run all tests
      run: cargo test --all-features

    - name: Cleanup after tests
      run: cargo clean

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage report
      run: cargo tarpaulin --verbose -o=Html

    - uses: actions/upload-artifact@master
      with:
        name: coverage-report.html
        path: tarpaulin-report.html
